/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtivadoRouteImport } from './routes/ativado'
import { Route as DadosRouteImport } from './routes/dados'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as EvolucaoRouteImport } from './routes/evolucao'
import { Route as HojeRouteImport } from './routes/hoje'
import { Route as KpisRouteImport } from './routes/kpis'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as ProtocolosRouteImport } from './routes/protocolos'
import { Route as RecaidasRouteImport } from './routes/recaidas'
import { Route as SemaforoRouteImport } from './routes/semaforo'
import { Route as SemanaRouteImport } from './routes/semana'
import { Route as TerapiaRouteImport } from './routes/terapia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivadoRoute = AtivadoRouteImport.update({
  id: '/ativado',
  path: '/ativado',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosRoute = DadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucaoRoute = EvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const HojeRoute = HojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => rootRouteImport,
} as any)
const KpisRoute = KpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolosRoute = ProtocolosRouteImport.update({
  id: '/protocolos',
  path: '/protocolos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecaidasRoute = RecaidasRouteImport.update({
  id: '/recaidas',
  path: '/recaidas',
  getParentRoute: () => rootRouteImport,
} as any)
const SemaforoRoute = SemaforoRouteImport.update({
  id: '/semaforo',
  path: '/semaforo',
  getParentRoute: () => rootRouteImport,
} as any)
const SemanaRoute = SemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => rootRouteImport,
} as any)
const TerapiaRoute = TerapiaRouteImport.update({
  id: '/terapia',
  path: '/terapia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ativado': typeof AtivadoRoute
  '/dados': typeof DadosRoute
  '/diario': typeof DiarioRoute
  '/evolucao': typeof EvolucaoRoute
  '/hoje': typeof HojeRoute
  '/kpis': typeof KpisRoute
  '/plano': typeof PlanoRoute
  '/protocolos': typeof ProtocolosRoute
  '/recaidas': typeof RecaidasRoute
  '/semaforo': typeof SemaforoRoute
  '/semana': typeof SemanaRoute
  '/terapia': typeof TerapiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ativado': typeof AtivadoRoute
  '/dados': typeof DadosRoute
  '/diario': typeof DiarioRoute
  '/evolucao': typeof EvolucaoRoute
  '/hoje': typeof HojeRoute
  '/kpis': typeof KpisRoute
  '/plano': typeof PlanoRoute
  '/protocolos': typeof ProtocolosRoute
  '/recaidas': typeof RecaidasRoute
  '/semaforo': typeof SemaforoRoute
  '/semana': typeof SemanaRoute
  '/terapia': typeof TerapiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ativado': typeof AtivadoRoute
  '/dados': typeof DadosRoute
  '/diario': typeof DiarioRoute
  '/evolucao': typeof EvolucaoRoute
  '/hoje': typeof HojeRoute
  '/kpis': typeof KpisRoute
  '/plano': typeof PlanoRoute
  '/protocolos': typeof ProtocolosRoute
  '/recaidas': typeof RecaidasRoute
  '/semaforo': typeof SemaforoRoute
  '/semana': typeof SemanaRoute
  '/terapia': typeof TerapiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ativado'
    | '/dados'
    | '/diario'
    | '/evolucao'
    | '/hoje'
    | '/kpis'
    | '/plano'
    | '/protocolos'
    | '/recaidas'
    | '/semaforo'
    | '/semana'
    | '/terapia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ativado'
    | '/dados'
    | '/diario'
    | '/evolucao'
    | '/hoje'
    | '/kpis'
    | '/plano'
    | '/protocolos'
    | '/recaidas'
    | '/semaforo'
    | '/semana'
    | '/terapia'
  id:
    | '__root__'
    | '/'
    | '/ativado'
    | '/dados'
    | '/diario'
    | '/evolucao'
    | '/hoje'
    | '/kpis'
    | '/plano'
    | '/protocolos'
    | '/recaidas'
    | '/semaforo'
    | '/semana'
    | '/terapia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtivadoRoute: typeof AtivadoRoute
  DadosRoute: typeof DadosRoute
  DiarioRoute: typeof DiarioRoute
  EvolucaoRoute: typeof EvolucaoRoute
  HojeRoute: typeof HojeRoute
  KpisRoute: typeof KpisRoute
  PlanoRoute: typeof PlanoRoute
  ProtocolosRoute: typeof ProtocolosRoute
  RecaidasRoute: typeof RecaidasRoute
  SemaforoRoute: typeof SemaforoRoute
  SemanaRoute: typeof SemanaRoute
  TerapiaRoute: typeof TerapiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativado': {
      id: '/ativado'
      path: '/ativado'
      fullPath: '/ativado'
      preLoaderRoute: typeof AtivadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados': {
      id: '/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof DadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucao': {
      id: '/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof EvolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoje': {
      id: '/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof HojeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpis': {
      id: '/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof KpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolos': {
      id: '/protocolos'
      path: '/protocolos'
      fullPath: '/protocolos'
      preLoaderRoute: typeof ProtocolosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recaidas': {
      id: '/recaidas'
      path: '/recaidas'
      fullPath: '/recaidas'
      preLoaderRoute: typeof RecaidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semaforo': {
      id: '/semaforo'
      path: '/semaforo'
      fullPath: '/semaforo'
      preLoaderRoute: typeof SemaforoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semana': {
      id: '/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof SemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terapia': {
      id: '/terapia'
      path: '/terapia'
      fullPath: '/terapia'
      preLoaderRoute: typeof TerapiaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtivadoRoute: AtivadoRoute,
  DadosRoute: DadosRoute,
  DiarioRoute: DiarioRoute,
  EvolucaoRoute: EvolucaoRoute,
  HojeRoute: HojeRoute,
  KpisRoute: KpisRoute,
  PlanoRoute: PlanoRoute,
  ProtocolosRoute: ProtocolosRoute,
  RecaidasRoute: RecaidasRoute,
  SemaforoRoute: SemaforoRoute,
  SemanaRoute: SemanaRoute,
  TerapiaRoute: TerapiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}